# Generated by Django 4.1.1 on 2022-11-02 20:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0002_creatorpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorpost',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
