# Generated by Django 4.1.1 on 2022-11-11 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('creators', '0003_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatorfeed',
            name='id',
        ),
        migrations.AddField(
            model_name='creatorfeed',
            name='name',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='creatorfeed',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
