# Generated by Django 4.1.1 on 2022-11-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0003_creatorpost_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='creatorpost',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
