# Generated by Django 4.1.1 on 2022-11-03 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('creators', '0004_alter_creatorpost_image_alter_creatorpost_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorpost',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
