# Generated by Django 4.1.1 on 2022-11-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0005_alter_creatorfeed_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorfeed',
            name='link',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='creatorfeed',
            name='link1',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='creatorfeed',
            name='link2',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='creatorfeed',
            name='profileImg',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='creatorfeed',
            name='services',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
