# Generated by Django 4.1.1 on 2022-11-16 19:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('creators', '0006_alter_creatorfeed_link_alter_creatorfeed_link1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorfeed',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
